#!/usr/bin/php
<?php
/*
 * This file is part of PHPAutotest
 *
 * (c) Guillermo Gutiérrez Almazor <guille@ggalmazor.com>
 * (c) Luis Cordoval <cordoval@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

$pharFile = __DIR__ . '/autotest.phar';

if (file_exists($pharFile))
  unlink($pharFile);

$phar = new Phar($pharFile, 0, 'autotest.phar');
$phar->setSignatureAlgorithm(\Phar::SHA1);

$phar->startBuffering();

$phar->addFromString('bootstrap.php', file_get_contents('bootstrap.php'));
$phar->addFromString('lib/Autotest/Autotest.php', file_get_contents('lib/Autotest/Autotest.php'));
$phar->addFromString('lib/Autotest/Factory.php', file_get_contents('lib/Autotest/Factory.php'));
$phar->addFromString('lib/Autotest/PHPUnitAutotest.php', file_get_contents('lib/Autotest/PHPUnitAutotest.php'));
$phar->addFromString('lib/Autotest/PHPSpecAutotest.php', file_get_contents('lib/Autotest/PHPSpecAutotest.php'));
$phar->addFromString('lib/Autotest/BehatAutotest.php', file_get_contents('lib/Autotest/BehatAutotest.php'));

$phar->setStub(getStub());

$phar->stopBuffering();

exec("chmod +x {$pharFile}");

function getStub() {
  return <<<'EOF'
#!/usr/bin/php
<?php
/*
 * This file is part of PHPAutotest
 *
 * (c) Guillermo Gutiérrez Almazor <guille@ggalmazor.com>
 * (c) Luis Cordoval <cordoval@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
    
Phar::mapPhar('autotest.phar');

include('phar://autotest.phar/bootstrap.php');

list($file, $framework) = parseArguments($argv);

try {
  $autotest = Autotest\Factory::create($file, $framework);
} catch (\Exception $e) {
  die(printUsage($e->getMessage()));
}

while (true && $autotest) {
  $autotest->executeTest();
  while (!$autotest->canRetry()) {
    // we wait while prompting for retry key press
  }
}

function parseArguments($args) {
  if (3 == count($args))
      return array($args[2], $args[1]);
  if (2 == count($args))
      return array($args[1], null);
  die(printUsage("Wrong argument count"));
}

function printUsage($error) {
  return <<<EOT

    {$error}

    Usage:

    autotest <file/path>

    or

    autotest <phpunit|phpspec|behat> <file/path>


EOT;
}
__HALT_COMPILER();
EOF;
}
